<?php 
defined("_ALLOW") or die ("Access denied"); 
$cfg_title_site = 'Title Site'; 
$cfg_yahoo = ''; 
$cfg_mail = 'info@phannguyenit.com'; 
$cfg_mailname = 'Website Administrator'; 
$cfg_introcontact = '<div align="center"><!--[if gte mso 9]><xml>  <w:WordDocument>   <w:View>Normal</w:View>   <w:Zoom>0</w:Zoom>   <w:PunctuationKerning/>   <w:ValidateAgainstSchemas/>   <w:SaveIfXMLInvalid>false</w:SaveIfXMLInvalid>   <w:IgnoreMixedContent>false</w:IgnoreMixedContent>   <w:AlwaysShowPlaceholderText>false</w:AlwaysShowPlaceholderText>   <w:Compatibility>    <w:BreakWrappedTables/>    <w:SnapToGridInCell/>    <w:WrapTextWithPunct/>    <w:UseAsianBreakRules/>    <w:DontGrowAutofit/>   </w:Compatibility>   <w:BrowserLevel>MicrosoftInternetExplorer4</w:BrowserLevel>  </w:WordDocument> </xml><![endif]--><!--[if gte mso 9]><xml>  <w:LatentStyles DefLockedState="false" LatentStyleCount="156">  </w:LatentStyles> </xml><![endif]--><!--[if !mso]><div   classid="clsid:38481807-CA0E-42D2-BF39-B33AF135CC4D" id=ieooui></div> <style> st1\:*{behavior:url(#ieooui) } </style> <![endif]--> <!--  /* Style Definitions */  p.MsoNormal, li.MsoNormal, div.MsoNormal 	{mso-style-parent:""; 	margin:0in; 	margin-bottom:.0001pt; 	mso-pagination:widow-orphan; 	font-size:12.0pt; 	font-family:"Times New Roman"; 	mso-fareast-font-family:"Times New Roman";} @page Section1 	{size:8.5in 11.0in; 	margin:1.0in 1.25in 1.0in 1.25in; 	mso-header-margin:.5in; 	mso-footer-margin:.5in; 	mso-paper-source:0;} div.Section1 	{page:Section1;} --> <!--[if gte mso 10]> <style>  /* Style Definitions */  table.MsoNormalTable 	{mso-style-name:"Table Normal"; 	mso-tstyle-rowband-size:0; 	mso-tstyle-colband-size:0; 	mso-style-noshow:yes; 	mso-style-parent:""; 	mso-padding-alt:0in 5.4pt 0in 5.4pt; 	mso-para-margin:0in; 	mso-para-margin-bottom:.0001pt; 	mso-pagination:widow-orphan; 	font-size:10.0pt; 	font-family:"Times New Roman"; 	mso-ansi-language:#0400; 	mso-fareast-language:#0400; 	mso-bidi-language:#0400;} </style> <![endif]-->  </div><p align="center"><font size="3" color="#008000"><strong>C&ocirc;ng Ty TNHH Thảo Nguy&ecirc;n</strong></font></p><div align="center">  </div><p align="center">208 Nguyễn Đ&igrave;nh Chiểu, Phường 6, Quận 3, Tp.Hồ Ch&iacute; Minh, Việt Nam.</p><div align="center">  </div><p align="center">Tel: 084-8-39300785; 39330792&nbsp; Fax: 084-8-39330361</p><div align="center">  </div><p align="center">Director: Ms.Phuong</p><div align="center">  </div><p align="center">E-mail:&nbsp; <a href="mailto:thaonguyen.co.ltd@hcm.fpt.vn">thaonguyen.co.ltd@hcm.fpt.vn</a>&nbsp;&nbsp;&nbsp; </p><div align="center">  </div><p align="center">Website: <a href="http://www.thaonguyen.com.vn/">http://www.thaonguyen.com.vn</a></p><p align="center">&nbsp;</p><p align="center">&nbsp;</p>'; 
$cfg_introcontact_en = '<p>Please input follw field</p>'; 
$cfg_autoresponse = 1; 
$cfg_textresponse = "Cảm ơn bạn đ&atilde; li&ecirc;n hệ với ch&uacute;ng t&ocirc;i"; 
$cfg_textresponse_en = "<p>Thank you very much</p>"; 
?>